# Generated by Django 2.1 on 2020-07-13 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_menu', models.CharField(blank=True, max_length=32, null=True, verbose_name='一级菜单名')),
                ('menu_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='二级菜单名')),
                ('path', models.CharField(blank=True, max_length=64, null=True, verbose_name='菜单路径')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜单权限表',
                'verbose_name_plural': '菜单权限表',
            },
        ),
    ]
