# Generated by Django 2.1 on 2020-07-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='MenuPermission',
        ),
        migrations.AlterModelTable(
            name='menupermission',
            table='menu_permission',
        ),
    ]
