# Generated by Django 2.1 on 2020-07-14 02:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_menupermission_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_permission', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), size=None, verbose_name='角色权限列表')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_menu', to='system.Role', verbose_name='所属角色id')),
            ],
            options={
                'verbose_name': '角色权限表',
                'verbose_name_plural': '角色权限表',
                'db_table': 'role_permission',
            },
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='parent_menu',
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='path',
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='role',
        ),
        migrations.AddField(
            model_name='menupermission',
            name='menu_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='二级菜单key'),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='parent_menu_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='一级菜单key'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='menu_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='二级菜单名'),
        ),
    ]
