# Generated by Django 2.1 on 2020-07-14 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200714_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstMenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='一级菜单key')),
                ('menu_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='一级菜单名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '一级菜单权限表',
                'verbose_name_plural': '一级菜单权限表',
                'db_table': 'firstmenu_permission',
            },
        ),
        migrations.CreateModel(
            name='SecondMenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='二级菜单key')),
                ('menu_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='二级菜单名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_permission', to='system.FirstMenuPermission', verbose_name='所属一级菜单id')),
            ],
            options={
                'verbose_name': '二级菜单权限表',
                'verbose_name_plural': '二级菜单权限表',
                'db_table': 'secondmenu_permission',
            },
        ),
        migrations.DeleteModel(
            name='MenuPermission',
        ),
    ]
