# Generated by Django 2.1 on 2020-07-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200714_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstmenupermission',
            name='menu_name',
        ),
    ]
